### ISSUE TITLE
Update-Help : Unable to connect to Help content

### ISSUE THREAD

**Issue by jeffreymcclain** [tomohulk/WinSCP#102]
### Issue Description

The help content cannot be updated using the "Update-Help" cmdlet.
I noticed this the other day when running "Update-Help" against all my installed modules.

This is a very minor issue as I typically use your GitHub Wiki documentation instead, but I figured I would mention it anyways.

P.S.: I really appreciate you releasing this module as FOSS software and updating it regularly, if you accept donations I'd be happy to send you some beer money as thanks!

### Example

Update-Help -Name WinSCP

### Expected Output

The module's help content should be updated successfully.

### Actual Output

> Update-Help : Failed to update Help for the module(s) 'WinSCP' with UI culture(s) {en-US} : Unable to connect to Help content. The server on which Help content is stored might not be available. Verify that the server is available, or wait until the server is back online, and then try the command again.
> At line:1 char:1
> \+ update-help -name WinSCP
> \+ ~~~~~~~~~~~~~~~~~~~~~~~~
> \+ CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
>   \+ FullyQualifiedErrorId : UnableToConnect,Microsoft.PowerShell.Commands.UpdateHelpCommand

### WinSCP-PowerShell Version

5.15.1.0

### Environment

PowerShell v5.1; Windows 10, 64-bit, v1809 (LTSC)

**Comment by dotps1** [comment]
I don't currently support updateable help, the only help comes with the module as an .xml file.
