### ISSUE TITLE
 "No supported authentication methods available (server sent: publickey)

### ISSUE THREAD

**Issue by ericfran** [tomohulk/WinSCP#142]
_Please fill in the following fields, replacing the values inside the brackets `{{ }}`._

### Issue Description

Trying to access a SFTP server
and receive the following message
New-WinSCPSession: Exception calling "Open" with "1" argument(s): "No supported authentication methods available (server sent: publickey)
Authentication log (see session log for details):
Unable to load key file "C:\temp\private2-private.ppk" (PuTTY key format too new)

### Example

{{ Please provide an example of the code being used. }}

### Expected Output

{{ Please provide what expect to happen. }}

### Actual Output

{{ Please provide what actually happened. }}

### WinSCP-PowerShell Version

{{ Paste output of `Get-Module -Name WinSCP | Clip` here }}\

### Environment

Powershell 7.2 Windows 10

**Comment by tomohulk** [comment]
Closing due to lack of info.  No example of command provided.
