### ISSUE TITLE
Sync-WinSCPPath Option batch continue + option confirm off

### ISSUE THREAD

**Issue by nascentt** [tomohulk/WinSCP#152]
I've been searching for over an hour now and I can't seem to find out how to use:

```
option batch continue
option confirm off

```
with Sync-WinSCPPath

is this possible? How can it be done?

**Comment by martinprikryl** [comment]
https://winscp.net/eng/docs/scriptcommand_option#net

**Comment by tomohulk** [comment]
the `option confirm off` would be the way it is working by default so no need to specify that option.

I don't really have any plans to impliment the `option batch continue`.  This module is more of a wrapper, so there isn't a lot of core logic.
it looks like based on this you could implement it yourself, the `Session` object will already exist from the `New-WinSCPSession` cmdlet so you could just add the event handler: https://winscp.net/eng/docs/library_example_recursive_download_custom_error_handling
