### ISSUE TITLE
The term 'New-WinSCPSessionOptions' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by flaajimi** [tomohulk/WinSCP#154]
Hi,

I've downloaded an installed your plugin through the Install-Module cmdlet.

When I'm trying to run the code in your Example 1, with my server, user and password of course, I get a Powershell error:

New-WinSCPSessionOptions : The term 'New-WinSCPSessionOptions' is not recognized as the name of a cmdlet, function, script 
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.

Any ideas on what I might have configured incorrectly on my side, or is there a know problem that causes this error?

```
Import-Module WinSCP

$sessionOption = New-WinSCPSessionOption -HostName 10.10.10.207 -Protocol Sftp 

New-WinSCPSession -SessionOption $sessionOption
```

**Comment by flaajimi** [comment]
![2023-08-29_16h18_54](https://github.com/tomohulk/WinSCP/assets/22789071/175bd4b8-97fe-49df-84cc-4c60faabe05e)

**Comment by tomohulk** [comment]
Looks to me the module is not imported.  I see you have used the code to import it, but maybe it's not actually importing.  Use `List-Module` and see if it actually exists in your session.

**Comment by tomohulk** [comment]
I just grabbed the latest and seems to be working fine for me: 
<img width="559" alt="image" src="https://github.com/tomohulk/WinSCP/assets/52005101/20590094-7041-41a6-8725-1f82ad0725b8">

**Comment by flaajimi** [comment]
I Have anothe message :
![image](https://github.com/tomohulk/WinSCP/assets/22789071/f6f08111-63ef-4c44-ac0b-8a8faf699ba1)

Windows 8.1
![image](https://github.com/tomohulk/WinSCP/assets/22789071/ef56638b-5063-41c5-83a3-b5f41c01b175)

**Comment by tomohulk** [comment]
It seems like your system is blocking something perhaps. I am unable to reproduce this issue. 

But for starters I would update WMF, you have a very very old version of PowerShel.  WMF 5.1 came out quite long ago:  https://www.microsoft.com/en-us/download/details.aspx?id=54616

**Comment by flaajimi** [comment]
![2023-08-31_13h04_30](https://github.com/tomohulk/WinSCP/assets/22789071/5f3acac0-99b9-4189-b273-1c5afbdf615d)

**Comment by flaajimi** [comment]
I have a W8.1, the module is installed on 
![image](https://github.com/tomohulk/WinSCP/assets/22789071/93823e4b-9acb-4910-9208-3c56d86266fc)

**Comment by tomohulk** [comment]
Im not really sure what to say on this issue.  I can't reproduce it, and this module has been around for like 7+ years and has over 1M downloads and this issue hasn't been reported until now.  And the errors you are sharing suggest the module isn't even loading, so it not really anything to do with the logic inside it, its not getting that far.  This leaves me to believe it's something with your system.  And to me, it seems like something is being blocked.  maybe the script module as well as the assembly itself.  Check eventvwr and see if there is any errors that stand out there after you trying the `Import-Module` command.

Did you update your version of WMF?  5.0 is very old, 5.1 came out still in the days of windows 7.  you could also try pwsh.  this module is compatible with both.

**Comment by flaajimi** [comment]
It's OK now thanks
