### ISSUE TITLE
Session flag GiveUpSecurityAndAcceptAnySshHostKey not being set correctly with New-WinSCPSessionOption

### ISSUE THREAD

**Issue by briddochsrsd** [tomohulk/WinSCP#161]
_Please fill in the following fields:_

### Issue Description

After upgrading to 6.3.3 the -GiveUpSecurityAndAcceptAnySshHostKey flag does not seem to be setting in the session options in powershell object.

### Example

$sessionOption = New-WinSCPSessionOption -HostName $vendorSFTPHost -Protocol Sftp -Credential $vendorCred -GiveUpSecurityAndAcceptAnySshHostKey

### Expected Output

Object is set incorrectly. 

$sessionOption
SshHostKeyPolicy                             : GiveUpSecurityAndAcceptAny
GiveUpSecurityAndAcceptAnySshHostKey         : True

### Actual Output

$sessionOption
SshHostKeyPolicy                             : Check
GiveUpSecurityAndAcceptAnySshHostKey         : False

### WinSCP-PowerShell Version

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     6.3.3.0               WinSCP                              {ConvertTo-WinSCPEscapedString, Copy-WinSCPItem, …

### Environment

Windows server 2022/Windows 11
PS 5 or 7

### Notes
6.3.2 works correctly still. 

Work around can issue this command in scripts after creating object to correct this issue.
$sessionoption.GiveUpSecurityAndAcceptAnySshHostKey = $true

**Comment by tomohulk** [comment]
If I had to guess it's because these are Type `Switch`.  So the way to get the value would be using the `IsPresent()` method.  Let me see what I can do.  At worse case I can just make them `Bool` types.  Thanks for letting me know.

**Comment by briddochsrsd** [comment]
Thank you for looking into this.

**Comment by tomohulk** [comment]
Should be good once this build finishes up, you will need to change your code from `-GiveUpSecurityAndAcceptAnySshHostKey` to use `-SshHostKeyPolicy GiveUpSecurityAndAcceptAny`.
