### ISSUE TITLE
Sftp without a password

### ISSUE THREAD

**Issue by ChrisV-Newsday** [tomohulk/WinSCP#162]
### Issue Description

I have a SFTP connection that does not have a password.  It uses a Private Key / User name combo.  It works in the WinSCP Client but when I try to open a New-WinSCPSession and setting the New-WinSCPSessionOption's I either get prompted for a password if use "-Credential $userName" or if I leave -Credential out I get the error below

### Example

$session = New-WinSCPSession -SessionOption (New-WinSCPSessionOption -HostName $MBNY_SERVER -PortNumber 22 -Protocol Sftp -SshHostKeyFingerprint $Fingerprint -SshPrivateKeyPath $privateKey)

### Expected Output

Hoping for a successful connection

### Actual Output

Exception calling "Open" with "1" argument(s): "Authentication failed. Authentication log (see session log for details): Using username        
     | "anonymous". Server refused our key. Access denied.  Authentication failed."

### WinSCP-PowerShell Version
WinSCP v. 6.3.4 

### Environment
Windows 10 
PowerShell v. 7.4.1
WinSCP v. 6.3.4

**Comment by tomohulk** [comment]
It still needs to be a `[PSCredential]` object, even if the password is blank:

```powershell
$mycreds = New-Object System.Management.Automation.PSCredential("username", (new-object System.Security.SecureString))

$sessionOptions = New-WinSCPSessionOption -Credential $mycreds
```

**Comment by ChrisV-Newsday** [comment]
Thanks.   That worked like a charm!
